#include "../Chaos.h"

struct Kaos kaos = {
    .defineFunction = defineFunction,
    .getVariableBool = getVariableBool,
    .getVariableInt = getVariableInt,
    .getVariableFloat = getVariableFloat,
    .getVariableString = getVariableString,
    .getListLength = getListLength,
    .getListElementBool = getListElementBool,
    .getListElementInt = getListElementInt,
    .getListElementFloat = getListElementFloat,
    .getListElementString = getListElementString,
    .copyListElement = copyListElement,
    .getListElementType = getListElementType,
    .getDictLength = getDictLength,
    .getDictKeyByIndex = getDictKeyByIndex,
    .getDictElementBool = getDictElementBool,
    .getDictElementInt = getDictElementInt,
    .getDictElementFloat = getDictElementFloat,
    .getDictElementString = getDictElementString,
    .copyDictElement = copyDictElement,
    .getDictElementType = getDictElementType,
    .returnVariableBool = returnVariableBool,
    .returnVariableInt = returnVariableInt,
    .returnVariableFloat = returnVariableFloat,
    .returnVariableString = returnVariableString,
    .createVariableBool = createVariableBool,
    .createVariableInt = createVariableInt,
    .createVariableFloat = createVariableFloat,
    .createVariableString = createVariableString,
    .startBuildingList = startBuildingList,
    .returnList = returnList,
    .startBuildingDict = startBuildingDict,
    .returnDict = returnDict,
    .returnComplex = returnComplex
};
